import React from 'react'
import Login from '../components/Login'
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export default function log() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.back}>
        <Login />
      </main>

      <footer>

      </footer>
    </div>
  )
}
